apiVersion: apps/v1
kind: Deployment
metadata:
  name: sjfid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sjfid
  template:
    metadata:
      labels:
        app:sjfid
    spec:
      containers:
      - image: okteto.dev/sjfid:latest
        name: sjfid
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "f0479dcf-8185-484c-ad89-d3a79c7ae169"
        - name: Vless_Path
          value: "/vl5h6355"
        - name: Vmess_UUID
          value: "f0479dcf-8185-484c-ad89-d3a79c7ae169"
        - name: Vmess_Path
          value: "/vm1666-o9"
        - name: Share_Path
          value: "/v2link"
